version: "1.0.0"
services:
  api:
    build: ./api
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    volumes:
      - ./api:/app
      - /app/node_modules/
  react:
    build: ./react-app
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8080/
    volumes:
      - ./react-app:/app
      - /app/node_modules/
    stdin_open: true
    depends_on:
      - api

